### ISSUE TITLE
提交文章时提示 app is not defined

### ISSUE THREAD

**Issue by yaokai** [TencentCloudBase/tcb-demo-blog#2]
![20180913234538](https://user-images.githubusercontent.com/5572915/45499524-2dc75c80-b7af-11e8-9b8d-6dd66065de44.png)

请问这是怎么回事

**Comment by pzkj** [comment]
修改:  cloud/functions/addblog/index.js  文件 19 行
```javascript
 const db = app.database();
```
改为:
```javascript
 const db = cloud.database();
```

**Comment by lcxfs1991** [comment]
@pzkj is right。
